[project]
name = "00-search-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch",
    "minsearch>=0.0.4",
    "notebook",
    "openai",
    "pandas>=2.3.1",
    "scikit-learn",
    "tdqm",
]
