#!/bin/bash -e

# Pull the latest Qdrant image
docker pull qdrant/qdrant:v1.15.1

# Run the container with persistent storage
docker run -p 6333:6333 -p 6334:6334 \
    -v "$(pwd)/qdrant_storage:/qdrant/storage:z" \
    qdrant/qdrant
